### ISSUE TITLE
npm start, not reading `Import x from 'x'` in gulpfile

### ISSUE THREAD

**Issue by jrhii** [jacobgardner/hack-and-slash#11]
I am having syntax error issues that seem to stem from using es6's `import` statement.  Am I missing an unlisted dependency?

Also, are `babel-preset-es2015` and `eslint` dependencies that need to be installed?

[npm-debug.txt](https://github.com/jacobgardner/hack-and-slash/files/577438/npm-debug.txt)

**Comment by jacobgardner** [comment]
I'll add eslint, but it shouldn't be causing this.  That preset should be included with stage 1 I believe.  I'll wipe my repo and see if I can reproduce your error

**Comment by jacobgardner** [comment]
![image](https://cloud.githubusercontent.com/assets/245622/20100416/0d95bc08-a583-11e6-916e-2cf928985b13.png)

**Comment by jacobgardner** [comment]
Fixed by  53543be
